project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "YOUR PROJECT TITLE - changed"
  author:
    - AUTHOR1 (UNI1) me
    - AUTHOR2 (UNI2) big bird
  repo-url: https://github.com/ad4277/payroll
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    # theme: cosmo
    theme: darkly
    code-fold: true


