project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Fire and Police Department Payroll"
  author:
    - Alex J (ad4277)
  repo-url: https://github.com/ad4277/payroll
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd
    - appendix.qmd
    # - resultsdraft1.qmd
    # - resultsdraft2.qmd
    # - resultsdraft3.qmd
    

format:
  html:
    theme: cosmo
    # theme: darkly
    # theme: Litera
    code-fold: true
    # toc: true
    # toc-depth: 3
    toc-expand: true
    
    


